name: Publish Ruby Gem
on:
  workflow_call:
    inputs:
      gem-name:
        description: "Name of the gem to be published"
        type: string
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Bundle Install
        run: |
          bundle config set --local without development test
          bundle install --jobs 4 --retry 3
        env:
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{secrets.GITHUB_TOKEN}}
      - name: Set Credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: Bearer ${GITHUB_TOKEN}\n" > $HOME/.gem/credentials
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Publish to GitHub Packages
        run: |
          export OWNER=$( echo ${{ github.repository }} | cut -d "/" -f 1 )
          export GEM_NAME=$( echo ${{ github.repository }} | cut -d "/" -f 2 )
          gem build ${{ inputs.gem-name }}.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
